### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jeffrey-xiao** [jeffrey-xiao/rafty_ex#1]
Tracking issue for TODOs

# Features

- [ ] Single server membership changes
- [ ] Joint membership changes
- [ ] In memory compaction/snapshotting

# Tests

- [x] Tests for `log/in_memory_store.ex` and `log/rocks_db_store.ex`
  - [x] Ensure log can be overwritten if terms differ
  - [x] Ensure old log is kept when existing logs are more up-to-date
- [x] Tests for `fsm/server.ex`
- [x] Tests for `timer.ex`
- [x] Run tests in parallel
  - [ ] Set configuration option for db path
- [ ] Chaos testing

# Improvements

- [ ] Add a separate message called `Heartbeat`. `Heartbeat` would trigger `AppendEntriesRequest` if the server is not up-to-date. 
- [ ] Add learner replica for catching up and passive participation
- [ ] Consider limiting the number of in-flight requests
- [ ] Validate configuration
